In [155]:
import sys
# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
  print("Hello, World!")
  print(f"Python version: {sys.version}")
else:
  print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


In [156]:
my_list = [1, 2, 3]
print("Original List:", my_list)
my_list.append(4)
print("Modified List:", my_list)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


In [157]:
age=23
pi= 3.14
temperature=-5.5
print("datatypeofvariableage=",type(age))
print("datatypeofvariablepi=",type(pi))
print("datatypeofvariabletemperature =",type(temperature))

datatypeofvariableage= <class 'int'>
datatypeofvariablepi= <class 'float'>
datatypeofvariabletemperature = <class 'float'>


In [158]:
name="Alice"
greeting="Hello"
address="123MainSt"
print("datatypeofthevariablename=",type(name))
print("datatypeofthevariablegreeting=",type(greeting))
print("datatypeofthevariableaddress=",type(address)) #sliceonlyoneelement
print("Thefirstletterofthenameis:",name[0])
print("Thelastletterofthe nameis:",name[-1]) #slicearangeofelements
print("Thesecondlettertothefourthofthenameis:",name[1:4])
print("Thefirsttwolettersofthenameare:",name[:2])
print("Substringstartingfromthethirdletteris:",name[2:])

datatypeofthevariablename= <class 'str'>
datatypeofthevariablegreeting= <class 'str'>
datatypeofthevariableaddress= <class 'str'>
Thefirstletterofthenameis: A
Thelastletterofthe nameis: e
Thesecondlettertothefourthofthenameis: lic
Thefirsttwolettersofthenameare: Al
Substringstartingfromthethirdletteris: ice


In [159]:
list1=[1,2,3,4]
mixed_list=[12,"Hello",True] #Listismutable
mixed_list[0]=False
mixed_list

[False, 'Hello', True]

In [160]:

colors = ("red", "green", "yellow", "blue")
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])


First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')


In [161]:
person = {"name":"John","age":30,"city":"London"}
print(f"Hello my name is {person["name"]}. I am {person["age"]} years old and I live at { person["city"]}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is John. I am 30 years old and I live at London.
All keys: ['name', 'age', 'city']
All values: ['John', 30, 'London']


In [162]:
unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


In [163]:
is_student = True
has_license = False
print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))
result = None

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


In [164]:
num = 10
if num > 0:
  print("Positive")
elif num == 0:
  print("Zero")
else:
  print("Non-positive")

Positive


In [165]:
x= 5
y= 10
if x>0 and y<20:
  print("Bothconditionsaretrue")
if x>0 or y>20:
  print("Atleastoneconditionistrue")
if not x==0:
  print("xisnotequalto 0")

Bothconditionsaretrue
Atleastoneconditionistrue
xisnotequalto 0


In [166]:
#Definetwobooleanvariables
a= True
b= False #Usingthe’and’operator
if a and b:
  print("BothaandbareTrue")
else:
  print("EitheraorbisFalse")
  #Thiswillbeprinted #Usingthe’or’operator
if a or b:
  print("Atleastoneofa orbisTrue")#Thiswillbeprinted
else:
  print("BothaandbareFalse") #Usingthe’not’operator
if not a:
  print("aisFalse")#Thiswillnotbeprinted
else:
  print("aisTrue")#Thiswillbeprinted

EitheraorbisFalse
Atleastoneofa orbisTrue
aisTrue


In [167]:
#forloop:
fruits=["apple","banana","cherry"]
for fruit in fruits:
  print(fruit)
#Whileloop:
count=0
while count < 5:
    print("Count is:",count)
    count+=1
#Break
fruits=["apple","banana","orange"]
print("loop 1")
for fruit in fruits:
    print(fruit)
    if fruit=="apple":
        break
  #Continiue
print("loop2")
for fruit in fruits:
    if fruit=="apple":
      continue
    else:
      print(fruit)

apple
banana
cherry
Count is: 0
Count is: 1
Count is: 2
Count is: 3
Count is: 4
loop 1
apple
loop2
banana
orange


Problem - 1: Array Creation:


In [168]:
import numpy as np

In [169]:
#Initialize an empty array with size 2×2
arr1 = np.empty((2, 2))
print(arr1)

[[2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323]]


In [170]:
#Initialize an all-ones array with size 4×2
arr2 = np.ones((4, 2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [171]:
#Return a new array of given shape and type, filled with fill value
arr3 = np.full((3, 3), 7)
print(arr3)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [172]:
#Return a new array of zeros with same shape and type as a given array
arr4 = np.zeros_like(arr2)
print(arr4)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [173]:
#Return a new array of ones with same shape and type as a given array
arr5 = np.ones_like(arr2)
print(arr5)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [174]:
#Convert list into NumPy array
new_list = [1, 2, 3, 4]
arr6 = np.array(new_list)
print(arr6)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [175]:
import numpy as np


# 1.Create an array with values ranging from 10 to 49.
arr1 = np.arange(10, 50)
print(arr1)


# 2.Create a 3X3 matrix with values ranging from 0 to 8.
arr2 = np.arange(9).reshape(3, 3)
print(arr2)


# 3.Create a 3X3 identity matrix.
arr3 = np.eye(3)
print(arr3)


# 4.Create a random array of size 30 and find the mean of the array.
arr4 = np.random.random(30)
print("Array:", arr4)
print("Mean:", arr4.mean())


# 5.Create a 10X10 array with random values and find the minimum and maximum values.
arr5 = np.random.random((10, 10))
print("Minimum value:", arr5.min())
print("Maximum value:", arr5.max())


# 6.Create a zero array of size 10 and replace 5th element with 1.
arr6 = np.zeros(10)
arr6[4] = 1   # 5th element (index starts from 0)
print(arr6)


# 7.Reverse an array arr = [1,2,0,0,4,0].
arr7 = np.array([1, 2, 0, 0, 4, 0])
print(arr7[::-1])


# 8. Create a 2D array with 1 on border and 0 inside.
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print(arr8)


# 9. Create an 8X8 matrix and fill it with a checkerboard pattern.
arr9 = np.zeros((8, 8))
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print(arr9)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array: [5.90923584e-01 1.22802916e-02 8.30777605e-01 1.07101163e-01
 1.01396834e-01 1.84385282e-01 6.16802864e-01 7.11661851e-01
 6.18195020e-01 6.24132590e-01 9.42841614e-01 2.61680814e-01
 1.79465640e-01 9.93755648e-01 9.84696240e-02 2.30609489e-04
 4.97603795e-01 9.91555065e-01 4.97456853e-01 3.40508151e-01
 8.11310280e-01 6.93441159e-01 9.40041585e-01 9.24763732e-01
 1.32392413e-01 5.14594022e-02 7.21043949e-01 5.64759835e-01
 3.03950316e-01 6.94984993e-01]
Mean: 0.5013124187329708
Minimum value: 0.006671051302309605
Maximum value: 0.9960052459022442
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1

Problem - 3: Array Operations:

In [176]:
import numpy as np

#Given arrays
x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])


# 1.Add the two arrays (x and y).
print("Addition:\n", x + y)


# 2.Subtract the two arrays (x and y).
print("Subtraction:\n", x - y)


# 3.Multiply the array with any integer (multiply x by 2).
print("Multiplication:\n", x * 2)


# 4.Find the square of each element of the array (square of x).
print("Square of elements:\n", x ** 2)


# 5.Find the dot product between:
# (a) v and w
print("Dot product v.w:", np.dot(v, w))

# (b) x and v
print("Dot product x.v:\n", np.dot(x, v))

# (c) x and y
print("Dot product x.y:\n", np.dot(x, y))


# 6.Concatenate x and y along row.
print("Concatenate x and y (row):\n", np.concatenate((x, y), axis=0))

#Concatenate v and w along column.
print("Concatenate v and w (column):\n", np.vstack((v, w)).T)


#7. Concatenate x and v.
#This will give an error because x is 2D (2x2) and v is 1D (size 2).
#Dimensions must match for concatenation.

#print(np.concatenate((x, v)))   #gives error

Addition:
 [[ 6  8]
 [10 13]]
Subtraction:
 [[-4 -4]
 [-4 -3]]
Multiplication:
 [[ 2  4]
 [ 6 10]]
Square of elements:
 [[ 1  4]
 [ 9 25]]
Dot product v.w: 219
Dot product x.v:
 [29 77]
Dot product x.y:
 [[19 22]
 [50 58]]
Concatenate x and y (row):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w (column):
 [[ 9 11]
 [10 12]]


Problem - 4: Matrix Operations:

In [177]:
import numpy as np

#Given matrices
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

In [178]:
# 1.Prove A.A⁻¹ = I

A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)

print("A inverse:\n", A_inv)
print("A * A_inv:\n", result)

A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [179]:
# 2.Prove AB ≠ BA

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:\n", AB)
print("BA:\n", BA)

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


In [180]:
# 3.Prove (AB)^T = B^T A^T

AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)

print("(AB)^T:\n", AB_T)
print("B^T A^T:\n", BT_AT)

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]



1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.



In [181]:
import time
import numpy as np

size = 1000000

# Create two Python lists
list1 = list(range(size))
list2 = list(range(size))

# Element-wise addition using Python lists
start = time.time()

result_list = [list1[i] + list2[i] for i in range(size)]

end = time.time()
print("Time using Python lists:", end - start, "seconds")


# Convert lists to NumPy arrays
array1 = np.array(list1)
array2 = np.array(list2)

# Element-wise addition using NumPy
start = time.time()
result_array = array1 + array2

end = time.time()
print("Time using NumPy arrays:", end - start, "seconds")

Time using Python lists: 0.06443929672241211 seconds
Time using NumPy arrays: 0.002167940139770508 seconds


2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [154]:
import time
import numpy as np

size = 1000000

# Create two Python lists
list1 = list(range(size))
list2 = list(range(size))

# Element-wise multiplication using Python lists
start = time.time()

result_list = [list1[i] * list2[i] for i in range(size)]

end = time.time()
#print("the element wise multiplication using Python lists:",result_list)

print("Time using Python lists:", end - start, "seconds")


# Convert lists to NumPy arrays
array1 = np.array(list1)
array2 = np.array(list2)

# Element-wise multiplication using NumPy arrays
start = time.time()

result_array = array1 * array2

end = time.time()
#print("the element wise multiplication using NumPy array:",result_array)
print("Time using NumPy arrays:", end - start, "seconds")

Time using Python lists: 0.07392263412475586 seconds
Time using NumPy arrays: 0.0013470649719238281 seconds


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [183]:
import time
import numpy as np

size = 1000000

#Create two Python lists
list1 = list(range(size))
list2 = list(range(size))

#Dot product using Python lists
start = time.time()

dot_product_list = sum(list1[i] * list2[i] for i in range(size))

end = time.time()
print("Dot product using Python lists:", dot_product_list)
print("Time using Python lists:", end - start, "seconds")


#Convert lists to NumPy arrays
array1 = np.array(list1)
array2 = np.array(list2)

#Dot product using NumPy
start = time.time()

dot_product_numpy = np.dot(array1, array2)

end = time.time()
print("Dot product using NumPy:", dot_product_numpy)
print("Time using NumPy arrays:", end - start, "seconds")

Dot product using Python lists: 333332833333500000
Time using Python lists: 0.07753443717956543 seconds
Dot product using NumPy: 333332833333500000
Time using NumPy arrays: 0.001851797103881836 seconds


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [153]:
import time
import numpy as np
import random

size = 1000

# Create two 1000x1000 matrices using Python lists
matrix1 = [[random.randint(1,10) for _ in range(size)] for _ in range(size)]
matrix2 = [[random.randint(1,10) for _ in range(size)] for _ in range(size)]

# Matrix multiplication using Python lists
start = time.time()

result = [[0]*size for _ in range(size)]

for i in range(size):
    for j in range(size):
        for k in range(size):
            result[i][j] += matrix1[i][k] * matrix2[k][j]

end = time.time()

print("Time taken using Python lists:", end - start, "seconds")


# Convert to NumPy arrays
array1 = np.array(matrix1)
array2 = np.array(matrix2)

# Matrix multiplication using NumPy
start = time.time()

result_numpy = np.dot(array1, array2)

end = time.time()

print("Time taken using NumPy arrays:", end - start, "seconds")

Time taken using Python lists: 189.00938296318054 seconds
Time taken using NumPy arrays: 0.9550266265869141 seconds
